paqa_dither.c - initialize variable-sized arrays explicitly (#1052)
Initialize variable-sized arrays to zero explicitly, to avoid the following
error:

qa/paqa_dither.c:155:5: error: variable-sized object may not be initialized
  155 |     int histogram[kNumBins] = {};
      |     ^~~

$ gcc --version
gcc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110

(cherry picked from commit f2a9d6d6bc420831f05a8923a0d0afc5d7e32640)